### ISSUE TITLE
Megaraid_sas does not load in RockyLinux 8.6

### ISSUE THREAD

**Issue by TheCrockett** [elrepo/packages#246]
Talks about symbol versions not matching 

Im trying to figure out how to either rebuild the kernel with megaraid enabled for installation, or figure out how you guys built the DUD iso to see if it's just a matter of compiling against the current kernel (I think you would still need to publish a new revision).

The vmlinuz/initrd booted are the ones from Rocky 
http://download.rockylinux.org/pub/rocky/8.6/BaseOS/x86_64/os/isolinux/

![20220716_213533.jpg](https://user-images.githubusercontent.com/5264977/180097556-826a74ae-8e8d-4f0e-84af-7f5c4861e8d3.jpg)

Just a thought - it may make sense to name the file the versions of the kernel it's compatible with, or otherwise maintain a known-good article somewhere

**Comment by pjperry** [comment]
Unable to replicate an issue on RHEL9:

$ rpm -q kmod-megaraid_sas
kmod-megaraid_sas-07.719.03.00-1.el9_0.elrepo.x86_64

$ uname -a
Linux Build64R9 5.14.0-70.17.1.el9_0.x86_64 #1 SMP PREEMPT Tue Jun 14 11:32:10 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

$ lsmod | grep mega
megaraid_sas          184320  0

# dmesg | grep mega
[544417.986859] megaraid_sas: loading out-of-tree module taints kernel.
[544417.986983] megaraid_sas: module verification failed: signature and/or required key missing - tainting kernel
[544417.988910] megasas: 07.719.03.00-rc1

Everything looks fine so far - I cannot test the actual module as I do not have the hardware to test.

**Comment by tqhoang84** [comment]
The megaraid_sas driver has been rebuilt many times for EL 8.6 -> 8.10.
https://elrepo.org/linux/dud/el8/x86_64/
