### ISSUE TITLE
ib_qib does not load in RockyLinux 8.6

### ISSUE THREAD

**Issue by someone-somenet-org** [elrepo/packages#249]
unknown symbols prevent the loading of `ib_qib` :(

It seems similar to the megaraid issue #246

Unfortunately rebuilding the kernel with said module is not really possible, as even with various patches applied, it wont build.
But then: the Debian folks ship that module by default, so it should be possible to make it run for someone who knows both kernel trees better than me. ;)

**Comment by toracat** [comment]
We have deprecated the kmod-ib_qib package because it does not build on EL 8.6. Please see:

https://elrepo.org/bugs/view.php?id=1232

**Comment by tqhoang84** [comment]
The issue was re-opened and resolved with backported ib_qib driver for EL 8.10.
