### ISSUE TITLE
kmod-drbd84 should be rebuilt against kernel-core-4.18.0-448.el8.x86_64

### ISSUE THREAD

**Issue by bubble75** [elrepo/packages#252]
Fresh installation of Centos Stream 8
kernel 4.18.0-425.10.1.el8_7.x86_64 is not longer available, and install of kmod-drbd84 pulls in old kernel-core-4.18.0-408.el8.x86_64 because it requires kABI kernel(put_devmap_managed_page) = 0xde9d724c, which is missing in the current kernel-core-4.18.0-448.el8.x86_64.
weak-modules does not make drbd.ko available for that old version for some reason too.
So, after the installation I see no weak links:
find /lib/modules -name drbd.ko
/lib/modules/4.18.0-425.10.1.el8_7.x86_64/extra/drbd84/drbd.ko`
and it is impossible to use drbd at all, because it is compatible only with kernel which does not exist anymore.

**Comment by toracat** [comment]
We, ELRepo, do not support CentOS Stream kernels. 

You may want to ask the CentOS kmods Sig. They provide kmods for CentOS Streams.

**Comment by bubble75** [comment]
Thank you very much for the prompt answer. Then, we'd go to Rocky.
