### ISSUE TITLE
EL 8.10 packages availability?

### ISSUE THREAD

**Issue by dygland** [elrepo/packages#255]
Hello!
Thank you for all hard work making theese packages available.

Since RHEL 8.10 now is released and this bug is resolved https://elrepo.org/bugs/view.php?id=1440, when will the packages move from testing to elrepo? 

Kind regards,

David

**Comment by toracat** [comment]
We are waiting for major rebuild projects to release their 8.10. I see that Alma Linux announced it today. I suppose Rocky Linux will follow very soon.

**Comment by dygland** [comment]
Thank you for your swift response!
